kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-service-config
data:
  someKey1: value1
  #reference: https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.0.RC1/reference/html/#kubernetes-native-service-discovery

  nextService: catalog-service.default.svc.cluster.local:8080

  elasticsearchService: elasticsearch-service.default.svc.cluster.local:8080

  aptService: apt-service.default.svc.cluster.local:8080