apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service

    spec:
      containers:
        - name: catalog-service
          image: brianbwengye/catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: catalog-service-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: catalog-service-config
                  key: nextService
            - name: APT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: catalog-service-config
                  key: aptService
            - name: ELASTICSEARCH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: catalog-service-config
                  key: elasticsearchService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: catalog-service-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: catalog-service-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8081"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-service-secrets
                  key: mysql-root-password